### ISSUE TITLE
Unexpected token a in JSON at position 1

### ISSUE THREAD

**Issue by tomkerkhove** [cschleiden/replace-tokens#15]
I have a action run which is [failing](https://github.com/azure-deprecation/infrastructure/runs/3537515676?check_suite_focus=true) with error "Unexpected token a in JSON at position 1" and I'm not sure what the cause is.

Is there a way to get more information?

**Comment by n3wt0n** [comment]
Is this running on Windows runners or Linux runners?

**Comment by tomkerkhove** [comment]
It was on Linux

**Comment by cschleiden** [comment]
I cannot see the run you linked. Could you add information how you configured the action in your workflow file?

**Comment by tomkerkhove** [comment]
It looks like I have deleted this run as I forgot I have opened this one.

I will close it and re-open when I re-test this action - Sorry for the confusion.
