### ISSUE TITLE
Become a verified creator

### ISSUE THREAD

**Issue by jonas-lomholdt** [cschleiden/replace-tokens#19]
We use this action in our org for plenty of things, unfortunately due to certain restrictions we need to allow-list it because it's not published as a verified creator. That means for each version change we would need to go through a new approval process.

I couldn't find allot of documentation around becoming verified creator, maybe someone knows if this is feasible? 

Thanks!

**Comment by cschleiden** [comment]
I'd have to move the action to an organization and follow the steps here: https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

Maybe something for the future, but not planning to do that anytime soon.

**Comment by jonas-lomholdt** [comment]
Fair enough, thanks @cschleiden.
