### ISSUE TITLE
Is it time for a new tag?

### ISSUE THREAD

**Issue by tsvetelintsonev** [cschleiden/replace-tokens#26]
Hello guys,

I could see that you have upgraded to Node v16 yesterday and was thinking whether this is a good candidate for a tag bump up.

**Comment by jonas-lomholdt** [comment]
I would love to see a tag as well. Unfortunately I broke the build on the last PR (sorry) - fixed it here https://github.com/cschleiden/replace-tokens/pull/27 

Fingers crossed for a `2.0.0` tag :)

**Comment by tsvetelintsonev** [comment]
Awesome, thanks @jonas-lomholdt  :)

**Comment by cschleiden** [comment]
Created `v1.2` and moved the `v1` tag.
